using System;
using System.Collections.Generic;

namespace ChatbotApp2
{
    class Program
    {
        //  Memory storage
        static string userName = "";
        static string userInterest = "";
        static string userSentiment = "";

        // Keyword-based responses
        static Dictionary<string, List<string>> keywordResponses = new Dictionary<string, List<string>>()
        {
            { "password", new List<string>
                {
                    "Use strong, unique passwords for each account.",
                    "Avoid using personal details in your passwords.",
                    "Enable two-factor authentication wherever possible."
                }
            },
            { "scam", new List<string>
                {
                    "Watch out for unsolicited emails asking for info.",
                    "Scammers often impersonate trusted brands.",
                    "Report any suspicious communication to the authorities."
                }
            },
            { "privacy", new List<string>
                {
                    "Review your privacy settings on social media.",
                    "Limit how much personal information you share online.",
                    "Use encrypted apps for private communication."
                }
            },
            { "phishing", new List<string>
                {
                    "Don’t click links in suspicious emails.",
                    "Always check the sender’s email address.",
                    "Phishing often uses urgent language to trick you."
                }
            }
        };

        //  Sentiment-based responses
        static Dictionary<string, string> sentimentResponses = new Dictionary<string, string>()
        {
            { "worried", "It's totally normal to feel worried. Cyber threats are real, but you can take steps to stay safe." },
            { "curious", "Curiosity is the first step to awareness! Let's learn something useful." },
            { "frustrated", "I get it—cybersecurity can be confusing. But I'm here to help." }
        };

        //  Main chatbot logic
        static void Main(string[] args)
        {
            Console.WriteLine("CyberBot:" Hi! I'm your Cybersecurity Awareness Chatbot.");
            Console.WriteLine("Type 'exit' or 'quit' to end the conversation.");

            while (true)
            {
                Console.Write("\nYou: ");
                string input = Console.ReadLine().ToLower();

                if (input == "exit" || input == "quit")
                {
                    Console.WriteLine("CyberBot: Stay safe online. Goodbye!");
                    break;
                }

                string sentiment = DetectSentiment(input);
                if (!string.IsNullOrEmpty(sentiment))
                {
                    Console.WriteLine("CyberBot: " + sentimentResponses[sentiment]);
                    userSentiment = sentiment;
                }

                string keyword = RecognizeKeyword(input);
                if (!string.IsNullOrEmpty(keyword))
                {
                    string response = GetRandomResponse(keyword);
                    if (userInterest == keyword)
                    {
                        Console.WriteLine($"CyberBot: As someone interested in {keyword}, here's a tip: {response}");
                    }
                    else
                    {
                        Console.WriteLine("CyberBot: " + response);
                    }
                }
                else if (input.Contains("my name is"))
                {
                    userName = input.Substring(input.LastIndexOf("is") + 3).Trim();
                    Console.WriteLine($"CyberBot: Nice to meet you, {userName}!");
                }
                else if (input.Contains("interested in"))
                {
                    userInterest = input.Substring(input.LastIndexOf("in") + 3).Trim();
                    Console.WriteLine($"CyberBot: Got it! I'll remember that you're interested in {userInterest}.");
                }
                else
                {
                    Console.WriteLine("CyberBot: I'm not sure I understand. Can you try rephrasing?");
                }
            }
        }

        //  Detect sentiment based on keywords
        static string DetectSentiment(string input)
        {
            if (input.Contains("worried")) return "worried";
            if (input.Contains("curious")) return "curious";
            if (input.Contains("frustrated")) return "frustrated";
            return "";
        }

        //  Recognize cybersecurity keywords
        static string RecognizeKeyword(string input)
        {
            foreach (var key in keywordResponses.Keys)
            {
                if (input.Contains(key))
                    return key;
            }
            return "";
        }

        // Get a random response from the list
        static string GetRandomResponse(string keyword)
        {
            var responses = keywordResponses[keyword];
            Random rnd = new Random();
            int index = rnd.Next(responses.Count);
            return responses[index];
        }
    }
}
